In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [2]:
training_data=pd.read_csv(r"E:\kirti\coding ninjas\0000000000002429_training_titanic_x_y_train.csv")
testing_data=pd.read_csv(r"E:\kirti\coding ninjas\0000000000002429_test_titanic_x_test.csv")

In [3]:
training_data

Pclass                                            Name     Sex   Age  \
0         2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1         3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2         2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3         3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4         3                          Sutehall, Mr. Henry Jr    male  25.0   
..      ...                                             ...     ...   ...   
663       2                             Ilett, Miss. Bertha  female  17.0   
664       3                        Morrow, Mr. Thomas Rowan    male   NaN   
665       3                                   Bing, Mr. Lee    male  32.0   
666       3                     Strandberg, Miss. Ida Sofia  female  22.0   
667       3                  Murphy, Miss. Katherine "Kate"  female   NaN   

     SibSp  Parch           Ticket     Fare Cabin Embarked  Survived  
0        1      0           228414  26.0000   NaN        S         1  
1        0      0         A/5 2466   8.0500   NaN        S         0  
2        0      0           250655  26.0000   NaN        S         0  
3        0      4           349909  21.0750   NaN        S         0  
4        0      0  SOTON/OQ 392076   7.0500   NaN        S         0  
..     ...    ...              ...      ...   ...      ...       ...  
663      0      0       SO/C 14885  10.5000   NaN        S         1  
664      0      0           372622   7.7500   NaN        Q         0  
665      0      0             1601  56.4958   NaN        S         1  
666      0      0             7553   9.8375   NaN        S         0  
667      1      0           367230  15.5000   NaN        Q         1  

[668 rows x 11 columns]

In [4]:
training_data.describe(include='all')

Pclass                    Name   Sex         Age       SibSp  \
count   668.000000                     668   668  536.000000  668.000000   
unique         NaN                     668     2         NaN         NaN   
top            NaN  Hart, Miss. Eva Miriam  male         NaN         NaN   
freq           NaN                       1   427         NaN         NaN   
mean      2.296407                     NaN   NaN   29.700560    0.528443   
std       0.831638                     NaN   NaN   14.240257    1.080327   
min       1.000000                     NaN   NaN    0.670000    0.000000   
25%       2.000000                     NaN   NaN   21.000000    0.000000   
50%       3.000000                     NaN   NaN   29.000000    0.000000   
75%       3.000000                     NaN   NaN   38.250000    1.000000   
max       3.000000                     NaN   NaN   80.000000    8.000000   

             Parch   Ticket        Fare Cabin Embarked    Survived  
count   668.000000      668  668.000000   154      667  668.000000  
unique         NaN      524         NaN   119        3         NaN  
top            NaN  3101295         NaN    G6        S         NaN  
freq           NaN        6         NaN     4      484         NaN  
mean      0.407186      NaN   32.064552   NaN      NaN    0.402695  
std       0.854695      NaN   45.320835   NaN      NaN    0.490808  
min       0.000000      NaN    0.000000   NaN      NaN    0.000000  
25%       0.000000      NaN    7.925000   NaN      NaN    0.000000  
50%       0.000000      NaN   14.750000   NaN      NaN    0.000000  
75%       0.000000      NaN   31.275000   NaN      NaN    1.000000  
max       6.000000      NaN  512.329200   NaN      NaN    1.000000

In [5]:
train=training_data
train=train.drop('Name', axis=1)
train=train.drop('Ticket', axis=1)

In [6]:
print(train)

     Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked  Survived
0         2  female  29.0      1      0  26.0000   NaN        S         1
1         3    male   NaN      0      0   8.0500   NaN        S         0
2         2    male  39.0      0      0  26.0000   NaN        S         0
3         3  female  29.0      0      4  21.0750   NaN        S         0
4         3    male  25.0      0      0   7.0500   NaN        S         0
..      ...     ...   ...    ...    ...      ...   ...      ...       ...
663       2  female  17.0      0      0  10.5000   NaN        S         1
664       3    male   NaN      0      0   7.7500   NaN        Q         0
665       3    male  32.0      0      0  56.4958   NaN        S         1
666       3  female  22.0      0      0   9.8375   NaN        S         0
667       3  female   NaN      1      0  15.5000   NaN        Q         1

[668 rows x 9 columns]


In [7]:
train.loc[train['Sex']=='female', 'Sex']=0
train.loc[train['Sex']=='male', 'Sex']=1
train.loc[train['Embarked'].isnull(), 'Embarked']='S'
train.loc[train['Embarked']=='S', 'Embarked']=1
train.loc[train['Embarked']=='C', 'Embarked']=2
train.loc[train['Embarked']=='Q', 'Embarked']=3
train.loc[train['Cabin'].isnull(), 'Cabin']=0
train.loc[train['Cabin']!=0, 'Cabin']=1
train.loc[train['Age'].isnull(), 'Age']=train.loc[train['Age'].notnull() , 'Age'].mean()

In [8]:
train_data=train.values

In [9]:
x=train_data[:, :-1]
y=train_data[:, -1]

In [10]:
print(x.shape)
print(y.shape)

(668, 8)
(668,)


In [11]:
x

array([[2, 0, 29.0, ..., 26.0, 0, 1],
       [3, 1, 29.700559701492537, ..., 8.05, 0, 1],
       [2, 1, 39.0, ..., 26.0, 0, 1],
       ...,
       [3, 1, 32.0, ..., 56.4958, 0, 1],
       [3, 0, 22.0, ..., 9.8375, 0, 1],
       [3, 0, 29.700559701492537, ..., 15.5, 0, 3]], dtype=object)

In [12]:
pd.DataFrame(x)

0  1        2  3  4        5  6  7
0    2  0       29  1  0       26  0  1
1    3  1  29.7006  0  0     8.05  0  1
2    2  1       39  0  0       26  0  1
3    3  0       29  0  4   21.075  0  1
4    3  1       25  0  0     7.05  0  1
..  .. ..      ... .. ..      ... .. ..
663  2  0       17  0  0     10.5  0  1
664  3  1  29.7006  0  0     7.75  0  3
665  3  1       32  0  0  56.4958  0  1
666  3  0       22  0  0   9.8375  0  1
667  3  0  29.7006  1  0     15.5  0  3

[668 rows x 8 columns]

In [13]:
y

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,

In [14]:
train_data

array([[2, 0, 29.0, ..., 0, 1, 1],
       [3, 1, 29.700559701492537, ..., 0, 1, 0],
       [2, 1, 39.0, ..., 0, 1, 0],
       ...,
       [3, 1, 32.0, ..., 0, 1, 1],
       [3, 0, 22.0, ..., 0, 1, 0],
       [3, 0, 29.700559701492537, ..., 0, 3, 1]], dtype=object)

In [15]:
testing_data.describe(include='all')

Pclass                            Name   Sex         Age  \
count   223.000000                             223   223  178.000000   
unique         NaN                             223     2         NaN   
top            NaN  Hays, Miss. Margaret Bechstein  male         NaN   
freq           NaN                               1   150         NaN   
mean      2.345291                             NaN   NaN   29.694775   
std       0.850047                             NaN   NaN   15.398053   
min       1.000000                             NaN   NaN    0.420000   
25%       2.000000                             NaN   NaN   19.250000   
50%       3.000000                             NaN   NaN   27.000000   
75%       3.000000                             NaN   NaN   37.750000   
max       3.000000                             NaN   NaN   71.000000   

             SibSp       Parch   Ticket        Fare    Cabin Embarked  
count   223.000000  223.000000      223  223.000000       50      222  
unique         NaN         NaN      212         NaN       49        3  
top            NaN         NaN  CA 2144         NaN  B58 B60        S  
freq           NaN         NaN        3         NaN        2      160  
mean      0.506726    0.304933      NaN   32.622551      NaN      NaN  
std       1.169700    0.634108      NaN   61.062047      NaN      NaN  
min       0.000000    0.000000      NaN    0.000000      NaN      NaN  
25%       0.000000    0.000000      NaN    7.879200      NaN      NaN  
50%       0.000000    0.000000      NaN   12.475000      NaN      NaN  
75%       1.000000    0.000000      NaN   30.035400      NaN      NaN  
max       8.000000    2.000000      NaN  512.329200      NaN      NaN

In [16]:
test=testing_data
test=test.drop('Name', axis=1)
test=test.drop('Ticket', axis=1)

In [17]:
print(test)

     Pclass     Sex   Age  SibSp  Parch      Fare Cabin Embarked
0         2    male   8.0      1      1   36.7500   NaN        S
1         1  female  49.0      0      0   25.9292   D17        S
2         3    male   NaN      0      0    7.7375   NaN        Q
3         2  female  24.0      2      1   27.0000   NaN        S
4         1    male  36.0      0      0   26.2875   E25        S
..      ...     ...   ...    ...    ...       ...   ...      ...
218       3    male  20.0      1      0    7.9250   NaN        S
219       1    male  45.0      0      0   26.5500   B38        S
220       1  female  17.0      1      0  108.9000   C65        C
221       3    male  43.0      0      0    6.4500   NaN        S
222       2    male  36.5      0      2   26.0000    F2        S

[223 rows x 8 columns]


In [18]:
test.loc[test['Sex']=='female', 'Sex']=0
test.loc[test['Sex']=='male', 'Sex']=1
test.loc[test['Embarked'].isnull(), 'Embarked']='S'
test.loc[test['Embarked']=='S', 'Embarked']=1
test.loc[test['Embarked']=='C', 'Embarked']=2
test.loc[test['Embarked']=='Q', 'Embarked']=3
test.loc[test['Cabin'].isnull(), 'Cabin']=0
test.loc[test['Cabin']!=0, 'Cabin']=1
test.loc[test['Age'].isnull(), 'Age']=test.loc[test['Age'].notnull() , 'Age'].mean()

In [19]:
test_data=test.values

In [20]:
test_data.shape

(223, 8)

In [21]:
x_train=pd.DataFrame(x)
y_train=pd.DataFrame(y.ravel())

In [22]:
clf=LogisticRegression(solver='saga', max_iter=10000000, tol=0.000001)

In [23]:
x_train

0  1        2  3  4        5  6  7
0    2  0       29  1  0       26  0  1
1    3  1  29.7006  0  0     8.05  0  1
2    2  1       39  0  0       26  0  1
3    3  0       29  0  4   21.075  0  1
4    3  1       25  0  0     7.05  0  1
..  .. ..      ... .. ..      ... .. ..
663  2  0       17  0  0     10.5  0  1
664  3  1  29.7006  0  0     7.75  0  3
665  3  1       32  0  0  56.4958  0  1
666  3  0       22  0  0   9.8375  0  1
667  3  0  29.7006  1  0     15.5  0  3

[668 rows x 8 columns]

In [24]:
import numpy as np
x_train=np.array(x_train,dtype=float)
y_train=np.array(y_train,dtype=float)

In [25]:
clf.fit(x_train, y_train)

C:\Users\Vaibhav Kataria\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


LogisticRegression(max_iter=10000000, solver='saga', tol=1e-06)

In [26]:
predictions=clf.predict(test_data)

In [27]:
np.savetxt("E:\kirti\coding ninjas\predictions_logistic_regression.csv", predictions, delimiter=",", fmt='%.5f')